apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: csr-for-shanthi
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - client auth
  signerName: kubernetes.io/kube-apiserver-client
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1Z6Q0NBVDhDQVFBd0VqRVFNQTRHQTFVRUF3d0hjMmhoYm5Sb2FUQ0NBU0l3RFFZSktvWklodmNOQVFFQgpCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKelpGSzBHNVhydWFOdVd0V2JpVDlJbDlqSi9kL2RKellVenRuR3B2cW4rClRXN2JGK1ZZZFNIUW9DMUhHNlI0eVBscjJJdjZDTEo2eE1ZMFRudjR2NzJZUnJqN2ppbkg0MWdlOUdpTnkvN0EKVE4rbzlrQkZiREE3MGpsMGpMZjUvY2FsNDJDZVpMVldCSmt5UmlqRjh2NzVtWlZxOCtsTFZsenpnbzd6WTFjcwpnWHk3emk0UzZYSXppVERVQnhRK0RTSTlrSE0vOXYvMTBZMDMwMzFQYmthTVhqWVpvS3U4NlhNMDdUeDdheWFWCnNIZmJ2ay9kRHdXVDZlR3VacWtFdUJoMXNTM2tqeFdJdFBPS3JsTjdTZm8vbHo3SG9SWVpjNUhudXlaSjlvSy8KZUxudzJFUkZHRU9IZzltTjR3MEZ1VmN6N05xSkRKOFV6a0hza3dSZUtjRUNBd0VBQWFBQU1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNaT3lpUXFUTG82bnpaU3YwaFloUzJVU1RhL3EyWUFLNk1tbnVtQ0hCenEzQkJQWDFTClRsbzVkdGRsVDYrcWRaTDgydTNkMVNqZHpORjYvaG1SR3pRMEdON0pmWi9UMjhDM0VWS3RnZGNicjM5UHN6UFQKZzFxcVFVWjlWbFppUVNQVEFReFdTNnFjZGphRVRMaVQyTnFzcm1lVEtQWlp4YXRuTjZQUzlaZkpOWUMxUlg0SApxZ1RJR1FHN0xkRVEzMk9zUVNDVmVmTTdMWGRqdUJzckorUzQyd3puQi9QemtYMmFNeWkzdXoyczgzcXR1WldFClFNSWpkbDV6Skc4MjBvOFhXZ24zWGdlYUJ2SHROQU5sTzNlcEszOEowb1Qvbjc3ang5ZWFUL0FNaUVlc2ZGZVQKUDlLbDNsZGVBd0dPeDVHZ09HaElPVTdoWWErbCtPMjFpRGRkCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=